OFF_DUTY = "off_duty"
SLEEPER_BERTH = "sleeper_berth"
DRIVING = "driving"
ON_DUTY = "on_duty"

MAX_DRIVING_HOURS = 11
MAX_ON_DUTY_HOURS = 14
DRIVING_HOURS_BEFORE_BREAK = 8
MAX_CYCLE_HOURS = 70
MILES_BEFORE_FUEL = 1000
ARRIVAL_TOLERANCE_MILES = 0.001

REST_HOURS = 10
RESTART_HOURS = 34
BREAK_HOURS = 0.5
FUEL_HOURS = 0.5
INSPECTION_HOURS = 0.5
PICKUP_HOURS = 1
DROPOFF_HOURS = 1

FUEL_STATION_SEARCH_RADIUS_METERS = 5000
FUEL_STATION_SEARCH_STEP_MILES = 10
# Make its 900 because in tests appear that 1000 is not a safety margin to fuel at least one while driving 1000
FUEL_STOP_SPACING_MILES = 900

FUEL_AND_BREAK_FROM_HOURS = 6
FUEL_AND_BREAK_ON_DUTY_HOURS = 0.25
FUEL_AND_BREAK_OFF_DUTY_HOURS = 0.25

FUEL_ONLY = "fuel_only"
FUEL_AND_BREAK = "fuel_and_break"

MAP_ROUTE_POINTS_STEP = 10
